main: ce.ajneb97.ConditionalEvents
version: 4.65.1
name: ConditionalEvents
api-version: 1.13
softdepend: [PlaceholderAPI,Citizens,WorldGuardEvents,WorldGuard,ProtocolLib,DiscordSRV]
authors: ["Ajneb97", "Zowi"]
folia-supported: true

commands:
  conditionalevents:
    description: Main command of ConditionalEvents
    aliases: ce